// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sec.proto

package com.wat.grpc;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sec.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tag = 1;</code>
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string unit = 2;</code>
   */
  java.lang.String getUnit();
  /**
   * <code>string unit = 2;</code>
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string value = 4;</code>
   */
  java.lang.String getValue();
  /**
   * <code>string value = 4;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <code>string timestamp = 5;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 5;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
