// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sec.proto

package com.wat.grpc;

/**
 * Protobuf type {@code sec.DataList}
 */
public  final class DataList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sec.DataList)
    DataListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataList.newBuilder() to construct.
  private DataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataList() {
    dataList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DataList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              dataList_ = new java.util.ArrayList<com.wat.grpc.Data>();
              mutable_bitField0_ |= 0x00000001;
            }
            dataList_.add(
                input.readMessage(com.wat.grpc.Data.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        dataList_ = java.util.Collections.unmodifiableList(dataList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wat.grpc.SecProto.internal_static_sec_DataList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wat.grpc.SecProto.internal_static_sec_DataList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wat.grpc.DataList.class, com.wat.grpc.DataList.Builder.class);
  }

  public static final int DATALIST_FIELD_NUMBER = 1;
  private java.util.List<com.wat.grpc.Data> dataList_;
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  public java.util.List<com.wat.grpc.Data> getDataListList() {
    return dataList_;
  }
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  public java.util.List<? extends com.wat.grpc.DataOrBuilder> 
      getDataListOrBuilderList() {
    return dataList_;
  }
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  public int getDataListCount() {
    return dataList_.size();
  }
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  public com.wat.grpc.Data getDataList(int index) {
    return dataList_.get(index);
  }
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  public com.wat.grpc.DataOrBuilder getDataListOrBuilder(
      int index) {
    return dataList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dataList_.size(); i++) {
      output.writeMessage(1, dataList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dataList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dataList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wat.grpc.DataList)) {
      return super.equals(obj);
    }
    com.wat.grpc.DataList other = (com.wat.grpc.DataList) obj;

    boolean result = true;
    result = result && getDataListList()
        .equals(other.getDataListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDataListCount() > 0) {
      hash = (37 * hash) + DATALIST_FIELD_NUMBER;
      hash = (53 * hash) + getDataListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wat.grpc.DataList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wat.grpc.DataList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wat.grpc.DataList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wat.grpc.DataList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wat.grpc.DataList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wat.grpc.DataList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wat.grpc.DataList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wat.grpc.DataList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wat.grpc.DataList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wat.grpc.DataList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wat.grpc.DataList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wat.grpc.DataList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wat.grpc.DataList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sec.DataList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sec.DataList)
      com.wat.grpc.DataListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wat.grpc.SecProto.internal_static_sec_DataList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wat.grpc.SecProto.internal_static_sec_DataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wat.grpc.DataList.class, com.wat.grpc.DataList.Builder.class);
    }

    // Construct using com.wat.grpc.DataList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dataListBuilder_ == null) {
        dataList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dataListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wat.grpc.SecProto.internal_static_sec_DataList_descriptor;
    }

    @java.lang.Override
    public com.wat.grpc.DataList getDefaultInstanceForType() {
      return com.wat.grpc.DataList.getDefaultInstance();
    }

    @java.lang.Override
    public com.wat.grpc.DataList build() {
      com.wat.grpc.DataList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wat.grpc.DataList buildPartial() {
      com.wat.grpc.DataList result = new com.wat.grpc.DataList(this);
      int from_bitField0_ = bitField0_;
      if (dataListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dataList_ = java.util.Collections.unmodifiableList(dataList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dataList_ = dataList_;
      } else {
        result.dataList_ = dataListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wat.grpc.DataList) {
        return mergeFrom((com.wat.grpc.DataList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wat.grpc.DataList other) {
      if (other == com.wat.grpc.DataList.getDefaultInstance()) return this;
      if (dataListBuilder_ == null) {
        if (!other.dataList_.isEmpty()) {
          if (dataList_.isEmpty()) {
            dataList_ = other.dataList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataListIsMutable();
            dataList_.addAll(other.dataList_);
          }
          onChanged();
        }
      } else {
        if (!other.dataList_.isEmpty()) {
          if (dataListBuilder_.isEmpty()) {
            dataListBuilder_.dispose();
            dataListBuilder_ = null;
            dataList_ = other.dataList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dataListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataListFieldBuilder() : null;
          } else {
            dataListBuilder_.addAllMessages(other.dataList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wat.grpc.DataList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wat.grpc.DataList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.wat.grpc.Data> dataList_ =
      java.util.Collections.emptyList();
    private void ensureDataListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        dataList_ = new java.util.ArrayList<com.wat.grpc.Data>(dataList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wat.grpc.Data, com.wat.grpc.Data.Builder, com.wat.grpc.DataOrBuilder> dataListBuilder_;

    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public java.util.List<com.wat.grpc.Data> getDataListList() {
      if (dataListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dataList_);
      } else {
        return dataListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public int getDataListCount() {
      if (dataListBuilder_ == null) {
        return dataList_.size();
      } else {
        return dataListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public com.wat.grpc.Data getDataList(int index) {
      if (dataListBuilder_ == null) {
        return dataList_.get(index);
      } else {
        return dataListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder setDataList(
        int index, com.wat.grpc.Data value) {
      if (dataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataListIsMutable();
        dataList_.set(index, value);
        onChanged();
      } else {
        dataListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder setDataList(
        int index, com.wat.grpc.Data.Builder builderForValue) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder addDataList(com.wat.grpc.Data value) {
      if (dataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataListIsMutable();
        dataList_.add(value);
        onChanged();
      } else {
        dataListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder addDataList(
        int index, com.wat.grpc.Data value) {
      if (dataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataListIsMutable();
        dataList_.add(index, value);
        onChanged();
      } else {
        dataListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder addDataList(
        com.wat.grpc.Data.Builder builderForValue) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.add(builderForValue.build());
        onChanged();
      } else {
        dataListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder addDataList(
        int index, com.wat.grpc.Data.Builder builderForValue) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder addAllDataList(
        java.lang.Iterable<? extends com.wat.grpc.Data> values) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataList_);
        onChanged();
      } else {
        dataListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder clearDataList() {
      if (dataListBuilder_ == null) {
        dataList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dataListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public Builder removeDataList(int index) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.remove(index);
        onChanged();
      } else {
        dataListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public com.wat.grpc.Data.Builder getDataListBuilder(
        int index) {
      return getDataListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public com.wat.grpc.DataOrBuilder getDataListOrBuilder(
        int index) {
      if (dataListBuilder_ == null) {
        return dataList_.get(index);  } else {
        return dataListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public java.util.List<? extends com.wat.grpc.DataOrBuilder> 
         getDataListOrBuilderList() {
      if (dataListBuilder_ != null) {
        return dataListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dataList_);
      }
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public com.wat.grpc.Data.Builder addDataListBuilder() {
      return getDataListFieldBuilder().addBuilder(
          com.wat.grpc.Data.getDefaultInstance());
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public com.wat.grpc.Data.Builder addDataListBuilder(
        int index) {
      return getDataListFieldBuilder().addBuilder(
          index, com.wat.grpc.Data.getDefaultInstance());
    }
    /**
     * <code>repeated .sec.Data dataList = 1;</code>
     */
    public java.util.List<com.wat.grpc.Data.Builder> 
         getDataListBuilderList() {
      return getDataListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.wat.grpc.Data, com.wat.grpc.Data.Builder, com.wat.grpc.DataOrBuilder> 
        getDataListFieldBuilder() {
      if (dataListBuilder_ == null) {
        dataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.wat.grpc.Data, com.wat.grpc.Data.Builder, com.wat.grpc.DataOrBuilder>(
                dataList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        dataList_ = null;
      }
      return dataListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sec.DataList)
  }

  // @@protoc_insertion_point(class_scope:sec.DataList)
  private static final com.wat.grpc.DataList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wat.grpc.DataList();
  }

  public static com.wat.grpc.DataList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataList>
      PARSER = new com.google.protobuf.AbstractParser<DataList>() {
    @java.lang.Override
    public DataList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DataList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wat.grpc.DataList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

