// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sec.proto

package com.wat.grpc;

public interface DataListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sec.DataList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  java.util.List<com.wat.grpc.Data> 
      getDataListList();
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  com.wat.grpc.Data getDataList(int index);
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  int getDataListCount();
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  java.util.List<? extends com.wat.grpc.DataOrBuilder> 
      getDataListOrBuilderList();
  /**
   * <code>repeated .sec.Data dataList = 1;</code>
   */
  com.wat.grpc.DataOrBuilder getDataListOrBuilder(
      int index);
}
