// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sec.proto

package com.wat.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sec.Empty)
    com.google.protobuf.MessageOrBuilder {
}
