// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sec.proto

package com.wat.grpc;

public final class SecProto {
  private SecProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sec_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sec_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sec_DataList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sec_DataList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sec_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sec_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsec.proto\022\003sec\"X\n\004Data\022\013\n\003tag\030\001 \001(\t\022\014\n" +
      "\004unit\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\r\n\005valu" +
      "e\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\t\"\'\n\010DataList\022\033" +
      "\n\010dataList\030\001 \003(\0132\t.sec.Data\"\007\n\005Empty2_\n\007" +
      "Greeter\022%\n\010SendData\022\r.sec.DataList\032\n.sec" +
      ".Empty\022-\n\016SendStreamData\022\r.sec.DataList\032" +
      "\n.sec.Empty(\001B\032\n\014com.wat.grpcB\010SecProtoP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sec_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sec_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sec_Data_descriptor,
        new java.lang.String[] { "Tag", "Unit", "Description", "Value", "Timestamp", });
    internal_static_sec_DataList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sec_DataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sec_DataList_descriptor,
        new java.lang.String[] { "DataList", });
    internal_static_sec_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sec_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sec_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
